### ISSUE TITLE
File Upload

### ISSUE THREAD

**Issue by DoubleSentinel** [HE-Arc/WebGaL#14]
use https://github.com/Chive/django-multiupload to upload projects from users

**Comment by DoubleSentinel** [comment]
I'm having a new issue @greut , the following shows up when trying to upload a file of 23.5MB: 

![image](https://cloud.githubusercontent.com/assets/9153038/25065170/aae59754-220a-11e7-9723-2d6a64c10b59.png)

**Comment by greut** [comment]
Probably, it'll configure the proxy and let you configure your instance of nginx.

**Comment by greut** [comment]
Done.
fyi:
- on srvz: `nginx version: nginx/1.9.10`
- your's: `nginx version: nginx/1.10.1 (Ubuntu)`
